[PHP]
extension_dir = "C:\php-8.4.21-nts-Win32-vs17-x64\ext"
extension = openssl
extension = curl
extension = fileinfo
extension = mbstring
extension = zip
extension = pdo_pgsql
extension = pgsql
extension = pdo_sqlite
